services:
  - type: web
    name: baileys-laravel
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: LOG_CHANNEL
        value: stderr