services:
  - type: web
    name: baileys-laravel
    env: docker              # MUDANÇA: Agora é docker!
    plan: free
    region: oregon
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_ENV
        value: production
      - key: LOG_CHANNEL
        value: stderr
      - key: PORT
        value: 8080          # O Docker precisa de uma porta padrão